
import { ReactNode, FC } from 'react';
import Head from 'next/head';

import { Navbar } from '../Navbar';
import styles from './MainLayout.module.css';

type Props = {
  children?: ReactNode;
}

export const MainLayout: FC<Props> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextjsApp | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={styles.main}>
        { children }
      </main>
    </div>
  )
}
